version: "3.9"
services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8004:8004"
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://expensebuddy-backend-1:8004
      - PORT=3001
    depends_on:
      - backend
