version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8001
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - backend
