services:
  backend:
    build:
      context: ./backend
    ports:
      - "8004:8004"
    volumes:
      - ./backend/expenses.db:/app/expenses.db
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - expensebuddy-network
    
  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8004
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - expensebuddy-network

networks:
  expensebuddy-network:
    driver: bridge
