services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/expenses.db:/app/expenses.db
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - web_network
    
  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8004
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - web_network

networks:
  web_network:
    external: true
