name: Deploy to VM Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Navigate to project directory
          cd /home/smith/deploy/expensebuddy || exit 1
          
          # Pull latest changes
          git pull origin master
          
          # Stop existing services
          docker-compose -f docker-compose.prod.yml down || true
          
          # Build and start services
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Clean up unused Docker images
          docker image prune -f
          
          echo "Deployment completed successfully!"
        EOF
        
    - name: Health Check
      run: |
        sleep 30
        curl -f http://${{ secrets.SERVER_HOST }}:3000 || exit 1
        echo "Health check passed!"